name: Deploy

on:
  push:
    branches:
      - main
  workflow-dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    - name: Pulumi up
      uses: pulumi/actions@v4
      with:
        command: preview
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}