name: Continuous Deployment

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ steps.pulumi.outputs.url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
    - name: Pulumi up
      uses: pulumi/actions@v4
      id: pulumi
      with:
        command: up
        stack-name: dev
        work-dir: ./iac/
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
